### ISSUE TITLE
Deviation(s?) from CrowdNotifier

### ISSUE THREAD

**Issue by pdehaye** [notifyme-app/notifyme-app-ios#9]
NotifyMe implements the CrowdNotifier protocol. In promotional videos it appears as if NotifyMe stores a log of events attended. I think this is good, but it does deviate from the (first version and maybe the second) version of the protocol. 

For the sake of clarity and certainty, can you confirm that to be the case? Can you also proactively list explicitly in the README other deviations from the "vanilla" CrowdNotifier, and maybe explain why that choice was made? This would increase trust and avoid unnecessary discussions.

**Comment by simonroesch** [comment]
NotifyMe uses the CrowdNotifier protocol to notify people that checked-in at a venue. In addition to the CrowdNotifier protocol, upon check-out also a diary entry is stored. These diary entries are stored encrypted on the phone and help the user to remember where he was. Diary entries are automatically deleted after 14 days and can also be deleted earlier by the user manually. Thanks to the CrowdNotifier protocol it is still possible to notify users when they deleted the corresponding diary entry.

**Comment by pdehaye** [comment]
Thanks. 

Don't get why it is not upon check-in.

**Comment by MarcelWaldvogel** [comment]
It would be great that on checkout (and also globally), I have the option to disable the diary.
